spring.application.name=control-finance

# Spring config properties
spring.config.import=optional:file:.env[.properties]

server.port=${PORTA_SERVIDOR}

spring.datasource.url=${DB_MYSQL_USERNAME}
spring.datasource.username=${DB_MYSQL_PASSWORD}
spring.datasource.password=${DB_MYSQL_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# api.security.token.security=${JWT_SECRET:my-secret-key-123}

logging.level.org.springframework.security=DEBUG